name: "Post an Issue via CI"

on: 
  workflow_dispatch:
    inputs:
      title:
        description: 'Title for the new issue'
        required: true
        type: string
      body:
        description: 'Body for the new issue'
        required: true
        type: string

jobs:
  post-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Needed to federate tokens.
    steps:
      - name: "Grab tmp token"
        uses: octo-sts/action@v1.1.1
        id: octo-sts
        with:
          scope: Aj-vrod/bicho
          identity: dev

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
        
      - name: "Post issue"
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh issue create --title "${{ inputs.title }}" --body "${{ inputs.body }}"



